# Do not change the "definitions" section unless you know what you"re doing
# Usage: schematic manifest -c config.yml get -dt ClinicalAssay -t "Test Manifest" --jsonld ./NF.jsonld -s
asset_store:
  synapse:
    master_fileview_id: "syn28142805"
    manifest_basename: "synapse_storage_manifest"

manifest:
  manifest_folder: "manifests"
  title: "Gray_Foundation_Manifest"
  data_type: 

  # Clinical Data
    - "CohortCore"
    - "CohortCoreRFC"
    - "CohortCorePortal"

  # File Metadata
    - "ImagingLevel2"
    - "scATAC-seqLevel1"
    - "scRNA-seqLevel1"
    - "scRNA-seqLevel3"

model:
  location: "./GF.jsonld"

google_sheets:
  service_acct_creds: "creds.json"
  strict_validation: true
