name: main-ci

on:

  pull_request:   # default types: opened, synchronize, reopened
    branches: [main]
    paths:
      - 'modules/**'
      - '.github/workflows/main-ci.yml'
  
  workflow_dispatch:

env:
  SCHEMATIC_VERSION: 24.7.2 # please update .devcontainer as well until this can be set globally somewhere...
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository

      - name: Get skip flags
        id: check_skip_flags
        run: echo "HEAD_COMMIT_MESSAGE=$(git show -s --format=%s)" >> "$GITHUB_OUTPUT"
      
      - name: Setup custom build tools and make jsonld 
        shell: bash
        run: |
          bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)
          git clone --depth 1 https://github.com/anngvu/retold.git
          make

     # Set up supported python.
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.12' 
      
      - name: Setup schematic and do another convert pass
        id: schematic-convert
        run: |
          pip install schematicpy==${{ env.SCHEMATIC_VERSION }}
          pip show schematicpy
          schematic schema convert GF.jsonld
    
      - name: Commit files
        run: |
          git config user.email "gray-foundation-service@sagebase.org"
          git config user.name "gf-dcc-service"
          git commit -m "Build jsonld" -a
    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: ${{ github.event.pull_request.head.ref }}

# Additionally test PRs
  test:
    name: Test with schematic
    needs: [build]
    runs-on: ubuntu-22.04
    env:
      SCHEMATIC_SERVICE_ACCT_CREDS: ${{ secrets.SCHEMATIC_SERVICE_ACCT_CREDS }}
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.12' 
      
      - name: Setup schematic
        id: setup-schematic
        run: |
          pip install schematicpy==${{ env.SCHEMATIC_VERSION }}
          pip show schematicpy

      - name: Test generate googlesheets
        working-directory: tests/generate
        continue-on-error: true
        run: ./basic_templates.sh

      # TODO Step for test validation of data

      # TODO Step for test submission of data
      
      - name: Create test suite report
        working-directory: tests
        continue-on-error: true
        run: docker run -v $(pwd):/tests rocker/tidyverse R -e "rmarkdown::render('tests/test-suite-report.Rmd')"

      - name: Report on test suite as PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message-id: test-suite-report
          message-path: |
            tests/test-suite-report.md

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-logs-${{ matrix.schematic-version }}
          path: tests/**/logs
