# Build JSON-LD on pull requests with data model changes (starts with 'dm/')

name: schematic-schema-convert

on:
  pull_request:   # default types: opened, synchronize, reopened
    branches: [main]
    paths:
      - 'modules/**'

  workflow_dispatch:

env:
  schema_filename: GF.csv
  
jobs:
  build:
    if: startsWith(github.head_ref, 'dm/')
    runs-on: ubuntu-latest

    steps:
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
      
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository
 
      - name: Install schematic and convert schema
        shell: bash
        run: |
          pip3 install schematicpy
          make
    
      - name: Commit files
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git commit -m "Build csv, jsonld" -a
    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: ${{ github.event.pull_request.head.ref }}
